### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by eordano**

### CODE REVIEW

**Comment by federicobond** [comment]
Interesting choice.

**Comment by eordano** [comment]
MIT is not attractive for other companies that might want to use the license. Apache is lawyer-friendly and ensures that patents will not pose an issue. 

http://en.swpat.org/wiki/Patent_clauses_in_software_licences#Apache_License_2.0

**Comment by maraoz** [comment]
Doesn't Apache prohibit from using the code in non-Apache codebases?

**Comment by maraoz** [comment]
That's why I always used MIT, seems more premissive in general

**Pull request merged**
